baseurl = "https://westphae.github.io/stratux"
languageCode = "en-us"
title = "AHRS for Stratux"
canonifyUrls = "true"
theme = "hugo-material-docs"
# Enable Google Analytics by entering your tracking id
#googleAnalytics = "UA-XXXXXXX-X"

[params]
    # General information
    author = "Eric Westphal"
    description = "stratux with AHRS"
    copyright = "MIT license"

    # Repository
    provider = "GitHub"
    repo_url = "https://github.com/westphae/stratux"

    version = "1.0.0"
    logo = "/img/AHRS_Screenshot.png"
    favicon = "/stratux/img/favicon.png"

    permalink = "#"

    # Custom assets
    custom_css = ["css/local.css"]
    custom_js  = []

    # Syntax highlighting theme
    highlight_css  = ""

[params.palette]
    primary = "red"
    accent  = "teal"

[params.font]
    text = "Roboto"
    code = "Roboto Mono"

[social]
    email = "eric@androidtestpilot.com"
    twitter = "EWestphal"
    github = "westphae"
    slack = "https://stratuxadsb.slack.com/team/bonanzaeric"


[[menu.main]]
    name   = "AHRS for Stratux"
    url    = "/"
    weight = 0
    pre    = ""

[[menu.main]]
    name = "How-To"
    url = "howto/"
    weight = 10
    pre = ""

[[menu.main]]
    name = "Release Notes"
    url = "release_notes/"
    weight = 15
    pre = ""

[[menu.main]]
    name = "Collaboration"
    url = "collaboration/"
    weight = 20
    pre = ""

[[menu.main]]
    name = "Plan"
    url = "plan/"
    weight = 30
    pre = ""


[blackfriday]
    smartypants = true
    fractions = true
    smartDashes = true
    plainIDAnchors = true
